services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: where-parts-app
    container_name: where-parts-app
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - elasticsearch
      - memcached # Добавляем зависимость от Memcached
    networks:
      - app-network
    environment:
      MEMCACHED_HOST: memcached  # Указываем hostname Memcached
      MEMCACHED_PORT: 11211      # Указываем порт Memcached

  db:
    image: mysql:8
    container_name: where-parts-db
    environment:
      MYSQL_ROOT_PASSWORD: wT8gn!RpC2p/z.M5
      MYSQL_DATABASE: where_parts_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: where-parts-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MAX_EXECUTION_TIME: 300
      MEMORY_LIMIT: 512M
      UPLOAD_LIMIT: 100M
      TZ: Europe/Moscow
      SESSION_SAVE_PATH: /tmp
    volumes:
      - ./my-php-settings.ini:/usr/local/etc/php/conf.d/my-php-settings.ini
    networks:
      - app-network

  python_converter:
    build: ./python_converter
    image: python_converter
    container_name: python_converter
    ports:
      - "8002:8002"
    env_file:
      - .env
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app-network

  memcached: # Добавляем сервис Memcached
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"  # Опционально:  публикуем порт для отладки (удалите в production)
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  esdata:
